### ISSUE TITLE
Update item date/time when file uploaded

### ISSUE THREAD

**Issue by johnkit** [girder/girder#1276] opened 2016-03-16 19:22 UTC
Using the girder html interface, I can upload a new version of a file from its item page. When I do that, I would like to mark the item as updated as well, that is, change the "Updated" date/time displayed for the item whenever an upload is made.

Is it possible to make that the default behavior for file upload, as well as edit & delete, from the html item page? Alternatively, can we make it an option on, for example, the "Replace file contents" panel?

**Comment by zachmullen** [comment] 2016-03-16 19:23
I'm fine with having the item updated stamp get touched when a file is replaced.

**Comment by brianhelba** [comment] 2016-04-08 06:02
This is a duplicate of #710. Closing to keep discussion centralized there.

**Closed by brianhelba** 2016-04-08 06:02 UTC
