### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by AaronV77** [girder/girder#2653] opened 2018-03-07 20:50 UTC
Creating a collections does not show in either my public or private folder in Girder live site.

**Comment by mgrauer** [comment] 2018-03-07 21:45
Hi @AaronV77 , thanks for the report.

A collection is a set of folders that does not live under any particular user, so a collection will not appear under your user's public or private folder. If you click on the collections list in the nav menu, you should see your new collection appear there (assuming you have completed the collection creation process).

**Comment by AaronV77** [comment] 2018-03-07 22:49
Hey @mgrauer, 

First, when you say "A collection is a set of folders that does not live under any particular user",  how is that so? When I click on the access control under a collection that I created, the permissions are under my name, so is it not safe to say that the collection is in my name? 

Second, then why is there a folders for public and private? What is expected to be added to this file? 

Third, should I create an enhancement issue, to add the ability to see all the collections that I have created, rather than search through the main collections tab in the nav?

Lastly, thanks for the response!

**Comment by mgrauer** [comment] 2018-03-07 23:09
I think it would help for you to read through the [Girder user guide](http://girder.readthedocs.io/en/latest/user-guide.html), as a common reference, and even so it is confusing to talk about.

Folders ultimately live under some root location, either a specific User or a specific Collection. Collections are top level objects and do not live under a User. Your User has by default two folders, a Public and a Private folder. You can get to your User's folder when you are logged in by clicking on the dropdown under your login name and then going to "my folders". 

Collections are not rooted under any User object. What you are seeing in access control is about permissions, so it is true that your User has ownership permissions on the collection that you created, but these collections do not reside in your User's space. You can change the access control of that collection to another user, but it will not change the fact that the collection is a top level object and does not reside under your user or another user's space.

You can think that there are several top level objects. Some are Users, and your User is one in particular. Other top level objects are Collections. Collections, because they are top level objects, have no parent object, so they do not have your User as a parent object.

There is by default a Public folder and a Private folder because we thought these would be a good starting point. You can put whatever data you want in each. The Private folder (by default, this can be changed) has access so that only your User can see the contents. The Public folder (by default, this can also be changed) has access so that anyone in the world can see the contents.

I am going to close this issue because the Collections are working as intended. Feel free to discuss further here or create a new issue if you see behavior that is not working as intended (based on reading the documentation of Girder) or if you think there should be an enhancement. Requesting a feature is good to let us know that something is desirable, but we can make no promises that we will actually implement any given feature.

**Closed by mgrauer** 2018-03-07 23:09 UTC
