### ISSUE TITLE
Add a config option to disable web client notifications

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#2639] opened 2018-03-05 19:36 UTC
This is mainly to preserve server side resources, ideally this logic could have a small API surface area. 

Perhaps just some quick error handling and cleanup on the client side as well.

**Comment by danlamanna** [comment] 2018-03-05 20:00
One thing that would be really nice in the future is a built in list of notifications that a user has received. This would be something like hangouts.google.com has, and we could load past events on initial page load for users.

**Comment by danlamanna** [comment] 2018-03-06 17:47
One approach here would be to use the [503 Service Unavailable](https://http.cat/503) status code if it's disabled. Then use [EventSource.onerror](https://developer.mozilla.org/en-US/docs/Web/API/EventSource/onerror) to gracefully close the event stream.

**Comment by zachmullen** [comment] 2018-03-06 18:12
I like the idea of the server responding in some way to indicate to the client that it should not attempt to reopen the stream. However, I'd prefer to use something other than 503, in order not to overload that signal, which could potentially be used in cases where the stream *should* be reopened later.

**Comment by zachmullen** [comment] 2018-03-06 18:33
Here are some alternatives:

* 4xx status, maybe 403
* A special header in the response
* A special event payload that indicates the client should not try to reconnect

**Comment by mgrauer** [comment] 2018-03-06 18:44
410 Gone ?
420 Enhance Your Calm?

**Comment by zachmullen** [comment] 2018-03-06 18:46
410 would be a fine choice. 420 is meant for rate limiting.

**Comment by cjh1** [comment] 2018-03-06 18:47
418 I am a teapot?

**Comment by brianhelba** [comment] 2018-03-06 20:38
This is a server error (the feature is not enabled on that particular Girder instance's server), so it needs to be a 5xx error code.

I think either of:
* [501 Not Implemented](https://httpstatusdogs.com/img/501.jpg)
  > The server does not support the functionality required to fulfill the request. This is the appropriate response when the server does not recognize the request method and is not capable of supporting it for any resource.

* [503 Service Unavailable](https://httpstatusdogs.com/img/503.jpg)
  > The server is currently unable to handle the request due to a temporary overloading or maintenance of the server. The implication is that this is a temporary condition which will be alleviated after some delay. If known, the length of the delay MAY be indicated in a Retry-After header. If no Retry-After is given, the client SHOULD handle the response as it would for a 500 response.
  > 
  >       Note: The existence of the 503 status code does not imply that a
  >       server must use it when becoming overloaded. Some servers may wish
  >       to simply refuse the connection.

would be reasonable.

We should also note that the condition is indeed semi-temporary, as it is possible that the server could be re-configured to support notifications in the future. Indeed, the behavior for web clients will likely be that they try to establish an SSE connection every time the page loads, then give up for the reminder of the page's session if the failure code is sent; refreshing the site would trigger a new connection attempt.

**Comment by zachmullen** [comment] 2018-03-06 20:44
Hm, I had thought of this more as a 4xx class of error, since it's not anything explicitly wrong with the server, but rather an instruction that a client behavior is invalid, but I see your point, so I'd be fine with 5xx. I'd be more comfortable with 501 than 503, though.

**Comment by zachmullen** [comment] 2018-03-06 20:46
To explain why I don't want to use 503, imagine a future in which Girder server is broken into microservices, and the notification is a microservice. In that scenario, the reverse proxy for the services might respond with a 503 if it can't connect to the notification service, but in that case, the client *should* probably attempt to reconnect later.

**Comment by brianhelba** [comment] 2018-03-06 21:34
I'm not *that* attached to 503, but the rationale for it holds even in the microservice example. If we know it will be coming up later (e.g. due to maintenance), we'd include a `Retry-After` header (which is a just a suggested interval, not a guarantee). If it's down because the microservice is misconfigured or not installed, then 503 without a header would still work, because it could always be fixed or installed in the future. Abstracted to the client's perspective in the present case, this logic still holds: the notification service *could* come up in the future, if the server's maintainer's decide to reconfigure the server to support it; indeed web clients will retry a connection on every startup.

In my understanding, "permanent" status codes (like [308 Permanent Redirect)](https://httpstatusdogs.com/img/308.jpg) are more for things where a policy is changed, and clients should ideally update themselves to never do request the old route again.

Honestly, all of the above rationale applies equally for 501 or 503, but I think it's been worthwhile exploring this because there's a lot of interesting potential for Girder to further leverage RESTful principals and status codes in responses (e.g. 404 instead of 400 for missing documents).

<sub>....Confirmed! [<sub>Girder is moving to microservices!</sub>](https://i.imgur.com/C8WPHxw.png)</sub>

**Comment by mgrauer** [comment] 2018-05-15 20:40
I'd like to bump this up in priority.

**Comment by brianhelba** [comment] 2018-05-16 13:27
I can work on a PR for this today.

**Closed** 2018-05-28 18:43 UTC
Labels: domain: web-client
