### ISSUE TITLE
Update 'create release' docs to include building Docker images

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#1837] opened 2017-03-08 16:33 UTC
It looks like our Dockerhub tags are looking a little weak: https://hub.docker.com/r/girder/girder/tags

Ideally we should have a Girder image tagged every release, and the master tag should be removed in favor of latest (as Docker convention).

**Comment by zachmullen** [comment] 2017-03-23 21:10
Duplicate of #786

**Closed by zachmullen** 2017-03-23 21:10 UTC
