### ISSUE TITLE
Add ability to install plugins from Ansible role

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#2271] opened 2017-08-09 02:22 UTC
Ideally the user could specify a list of paths or git paths and have `girder-install plugin` be run against them.

**Comment by mgrauer** [comment] 2017-08-09 13:26
There would also need to be a way to specify system dependencies tied to the plugin.

**Comment by zachmullen** [comment] 2017-08-09 13:37
@mgrauer what do you mean?

**Comment by mgrauer** [comment] 2017-08-09 13:45
This issue was migrated from a different repo which was intended for a very specific purpose, but doing this operation there was out of scope.  

The intention is to specify to Ansible to install a 3rd party Girder plugin, one that doesn't live in the Girder repo.  That 3rd party plugin might require some additional system package for building or execution.

For this to work you'd need to specify where to find the plugin to install it (e.g. a git path) and also any system-deps needed by that plugin, and then tell the Girder Ansible role to install/activate that plugin.

**Comment by danlamanna** [comment] 2017-08-09 14:14
The role would probably require callers to install the system packages
themselves, and just deal with git clone/girder-install.

**Comment by mgrauer** [comment] 2017-08-12 16:35
To try to add some clarity to waters I had previously muddled:

 * This should **not** install system deps, but should document that the user is responsible for getting them installed outside of the role, e.g. in their site playbook
 * This should probably not clone the plugin from git or copy it from some other location, to allow more flexibility to the user, this should also be documented that it is the user's responsibility
 * This should install the plugin, allowing for args to be passed to the install command `girder-install plugin`
 * This should **not** enable the plugin and rebuild the web client for the plugin, that is the responsibility of the user, this should also be documented

🌊

**Closed** 2017-09-06 19:32 UTC
Labels: domain: devops
