### ISSUE TITLE
Uglify failure stack trace is not printing newlines

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1127] opened 2015-12-03 16:55 UTC
When the Grunt uglify task fails, it produces some output like:
<pre>
Running "uglify:app" (uglify) task
{ message: 'Unexpected token: operator (&)',
  filename: '../../src/app.js',
  line: 1,
  col: 0,
  pos: 0,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/home/vagrant/girder/node_modules/grunt-contrib-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:1507:18)\n    at js_error (eval at <anonymous> (/home/vagrant/girder/node_modules/grunt-contrib-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:1515:11)\n    at croak (eval at <anonymous> (/home/vagrant/girder/node_modules/grunt-contrib-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2007:9)\n    at token_error (eval at <anonymous> (/home/vagrant/girder/node_modules/grunt-contrib-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2015:9)\n    at unexpected (eval at <anonymous> (/home/vagrant/girder/node_modules/grunt-contrib-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2021:9)\n    at expr_atom (eval at <anonymous> (/home/vagrant/girder/node_modules/grunt-contrib-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2528:9)\n    at maybe_unary (eval at <anonymous> (/home/vagrant/girder/node_modules/grunt-contrib-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2690:19)\n    at expr_ops (eval at <anonymous> (/home/vagrant/girder/node_modules/grunt-contrib-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2725:24)\n    at maybe_conditional (eval at <anonymous> (/home/vagrant/girder/node_modules/grunt-contrib-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2730:20)\n    at maybe_assign (eval at <anonymous> (/home/vagrant/girder/node_modules/grunt-contrib-uglify/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2754:20)' }
</pre>

Note that the ``stack`` trace output contains newlines and indenting, but these are escaped instead of being printed. This makes it much more difficult to read and interpret the stack trace, which contains useful information for debugging.

**Comment by brianhelba** [comment] 2015-12-03 16:55
Ping @jbeezley

**Comment by jbeezley** [comment] 2015-12-03 17:00
What arguments are you using with the `grunt` command?  I don't think I've ever seen output like that.  Usually you need to run `grunt --stack` to see the stack trace.

**Comment by jbeezley** [comment] 2015-12-03 17:05
Okay, I reproduced it.  That's normal grunt-uglify output.  Like I mentioned, you add the `--stack` flag to make the stack trace human readable.

**Comment by brianhelba** [comment] 2015-12-03 17:07
I'm just running ``npm install``. Can we make the ``--stack`` option automatically be added when things are run via ``npm install``?

**Comment by jbeezley** [comment] 2015-12-03 17:16
We can add it to the postinstall script.

Unless you have a bug in your grunt tasks, the stack trace won't generally give you an useful information.  In this case, the grunt ugilfy extension isn't exactly behaving well.  It should be catching the error and raising a `grunt.fail.fatal` instead for cleaner output.

I view the `--stack` option as more of a developer thing, where `npm install` is run by users.  On the other hand, I don't see why adding it is harmful in any way.  I'll let others decide.

**Comment by zachmullen** [comment] 2015-12-03 18:10
Does a newer version of `grunt-contrib-uglify` exist? Maybe we should upgrade if so.

**Comment by jbeezley** [comment] 2015-12-03 18:13
Yes, we are on `0.4`.  `0.11` is available.

**Comment by zachmullen** [comment] 2015-12-03 18:15
This seems as good as time as any to bump to that.

**Comment by zachmullen** [comment] 2015-12-03 18:16
I'll do that on my branch I'm about to push.

**Comment by zachmullen** [comment] 2015-12-07 14:49
Seems that latest `grunt-contrib-uglify` has not addressed this issue. Since this is a bug in an upstream, I'm marking it as "wontfix" for lack of a better label. Should I keep the issue open?

**Comment by brianhelba** [comment] 2015-12-07 16:55
I'll leave it up to @jbeezley . He understands the technical implications of trying some sort of workaround much better than I do.

This issue doesn't bother me personally, as my IDE gives me static analysis for free. I was reporting this as an advocacy for other (especially new) users who may find the output useful when trying to track down Uglify failures.

**Comment by jbeezley** [comment] 2015-12-07 17:07
I'll close it then.  It relates to upstream and isn't technically a bug, but rather an issue of user friendliness.  The stack trace provided isn't useful anyway:
```
Error
    at new JS_Parse_Error (/Users/jbeezley/git/girder/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (/Users/jbeezley/git/girder/node_modules/uglify-js/lib/parse.js:204:11)
    at croak (/Users/jbeezley/git/girder/node_modules/uglify-js/lib/parse.js:684:41)
    at token_error (/Users/jbeezley/git/girder/node_modules/uglify-js/lib/parse.js:688:9)
    at unexpected (/Users/jbeezley/git/girder/node_modules/uglify-js/lib/parse.js:694:9)
    at expr_atom (/Users/jbeezley/git/girder/node_modules/uglify-js/lib/parse.js:1201:9)
    at maybe_unary (/Users/jbeezley/git/girder/node_modules/uglify-js/lib/parse.js:1363:19)
    at expr_op (/Users/jbeezley/git/girder/node_modules/uglify-js/lib/parse.js:1385:33)
    at expr_op (/Users/jbeezley/git/girder/node_modules/uglify-js/lib/parse.js:1386:20)
    at expr_ops (/Users/jbeezley/git/girder/node_modules/uglify-js/lib/parse.js:1398:16)
```
The useful part is the rest of the error message telling you where the syntax error occurred.

**Closed by jbeezley** 2015-12-07 17:07 UTC
Labels: wontfix
