### ISSUE TITLE
Items showing as 3x the size of the files within them

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#1267] opened 2016-03-02 17:56 UTC
I spoke with @manthey about this, but wanted to formally start an issue for discussion.

If I upload a file as a new item on Girder (via data.kitware.com), the item appears to be 3x the size of the file. I am able to reproduce this using both the Girder CLI client as well as the web interface, and it (seemingly) happens on files of all sizes.

I can't reproduce this on my local machine (on revision ac1fa3f), but @manthey and I have both been able to reproduce it on data.kitware.com.

**Comment by zachmullen** [comment] 2016-03-16 19:15
I just reproduced this. I'm going to upgrade data.kitware.com (it needs it anyway), let's see if that fixes the problem.

**Comment by zachmullen** [comment] 2016-03-21 19:00
Just upgraded data.kitware.com and this is now fixed.

**Comment by manthey** [comment] 2016-03-21 19:01
@zachmullen Any idea what was the cause of the problem?

**Closed by zachmullen** 2016-03-21 19:00 UTC

**Comment by zachmullen** [comment] 2016-03-21 19:02
No clue...
