### ISSUE TITLE
How do you use the hashsum_download api?

### ISSUE THREAD

**Issue by nholthaus** [girder/girder#1651] opened 2016-10-24 23:24 UTC
I'm trying to use girder as a midas replacement/cmake externalData module storage. @mgrauer mentioned this could be done using the `hashsum_download` plugin, but there doesn't seem to be any documentation for it. 

Could you guys share an example curl command or something showing how to use it?

**Comment by mgrauer** [comment] 2016-10-25 03:07
@nholthaus I've got some docs in the works (actually I'm not that far along), but for now I'll step you through this and hopefully this can be the basis of the docs I make.  Please report back if this works for you or you run into any trouble.

Caveats: currently this is only supported with a filesystem assetstore and `sha512` as the hash algorithm.

Here's a bit of [info](http://girder.readthedocs.io/en/latest/developer-cookbook.html?highlight=external#downloading-external-data-files-for-test-cases) about using External Data, but it is about using it with Midas.  This generally still applies when using it with Girder, though only files and not directories are currently supported.

1. Enable the `Hashsum download` plugin through the Girder Admin Console / Plugins page.  Then rebuild the web client code and restart the server.
2. Upload a file to girder.  Navigate to the Item, then click on the ℹ️  icon next to the file, which will show you the `id`, and since the `Hashsum download` plugin is enabled, the `sha512` field will also be displayed.
<img width="821" alt="screen shot 2016-10-24 at 10 28 15 pm" src="https://cloud.githubusercontent.com/assets/595023/19671111/5d383d8e-9a3a-11e6-8499-1d11adb492fb.png">
3. You can click on the 🔑 icon to download a hashfile, which will be the sha512 of the file, with the same name as the file, and an extension of `.sha512`, and use this for your CMake External Data file.
4. You can also use the API to get the hash of the file given the file ID, as seen in the swagger page for the endpoint `api/v1/file/580ec20cb0e9574bdcaf0a5a/hashsum_file/sha512`, where the file id comes from the specific file in Girder. This also shows you a curl command to use to call this API.
<img width="741" alt="screen shot 2016-10-24 at 10 29 19 pm" src="https://cloud.githubusercontent.com/assets/595023/19671216/309347aa-9a3b-11e6-94c8-7a59a9fb4418.png">
5. You can also use the API to download the file based on the hash, as seen in the swagger page for the endpoint `/api/v1/file/hashsum/sha512/d53773eaa50fa9cabbfebae1f16b3f32b6e67eed20ea0a683049efa625bc9a0362ec0426db0e58689a431d912d993482dc95dd1ec69e30f2038539e59fc3f6f9/download`, where the sha512 hash comes from the specific file in Girder.  This also shows you a curl command to use to call this API, though it sounds like you'd like to interact with this through the External Data mechanism in CMake.
<img width="727" alt="screen shot 2016-10-24 at 10 30 31 pm" src="https://cloud.githubusercontent.com/assets/595023/19671278/9cf36c40-9a3b-11e6-9be2-9cd2180eb414.png">
You can see an example of setting the URL to a Girder instance using `ExternalData_URL_TEMPLATES` [here](https://github.com/girder/girder/blob/57231f3984e268822359d72320580dac439093e2/tests/TestData.cmake#L17).

**Comment by nholthaus** [comment] 2016-10-25 12:34
So I get tripped up at the `Rebuild web code` step, which fails with an error (Due to proxy maybe?). When I try it on the command line, I get this:

```
GIRDER_LOCAL_FONTELLO_ARCHIVE=/root/girder/clients/web/static/built/fontello/fontello.zip girder-install web                           Connected to MongoDB: mongodb://localhost:27017/girder
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN grunt-webpack@1.0.18 requires a peer of webpack@1.x but none was installed.
npm WARN grunt-webpack@1.0.18 requires a peer of webpack-dev-server@1.x but none was installed.

> girder@2.0.0 build /root/girder_env/lib/python2.7/site-packages/girder
> grunt init && grunt "--env=prod" "--plugins=hashsum_download"

Using local fontello archive: /root/girder/clients/web/static/built/fontello/fontello.zip

Running "setup" task

Running "copy:fontello" (copy) task
Copied 1 files

Running "unzip:fontello" (unzip) task
Created "clients/web/static/built/fontello/" directory

Running "copy:swagger" (copy) task
Created 3 directories, copied 28 files

Done, without errors.
Using local fontello archive: /root/girder/clients/web/static/built/fontello/fontello.zip
Configuring plugin hashsum_download (plugin.json)

Running "plugin:hashsum_download" (plugin) task

Running "copy:plugin-hashsum_download" (copy) task


Running "stylus:swagger" (stylus) task
>> 1 file created.

Running "gitinfo" task

Running "file-creator:python-version" (file-creator) task
Writing file [girder/girder-version.json]
>> 1 file(s) written.

Running "file-creator:javascript-version" (file-creator) task
Writing file [clients/web/src/version.js]
>> 1 file(s) written.

Running "webpack:prod" (webpack) task
Version: webpack 2.1.0-beta.21         
                                             Asset       Size  Chunks             Chunk Names
                                 girder.app.min.js     913 kB       0  [emitted]  girder.app
  assets/glyphicons-halflings-regular-f4769f9b.eot    20.1 kB          [emitted]  
assets/glyphicons-halflings-regular-448c34a5.woff2      18 kB          [emitted]  
  assets/glyphicons-halflings-regular-e18bbf61.ttf    45.4 kB          [emitted]  
  assets/glyphicons-halflings-regular-89889688.svg     109 kB          [emitted]  
              assets/jsoneditor-icons-bf23347e.png    14.4 kB          [emitted]  
 assets/glyphicons-halflings-regular-fa277232.woff    23.4 kB          [emitted]  
            plugins/hashsum_download/plugin.min.js    16.6 kB       1  [emitted]  plugins/hashsum_download/plugin
                                 girder.ext.min.js    1.23 MB       2  [emitted]  girder.ext
                                girder.app.min.css    34.8 kB       0  [emitted]  girder.app
                                girder.ext.min.css     144 kB       2  [emitted]  girder.ext
           plugins/hashsum_download/plugin.min.css  128 bytes       1  [emitted]  plugins/hashsum_download/plugin

ERROR in girder.app.min.js from UglifyJs
SyntaxError: Unexpected token: punc ()) [girder.app.min.js:7866,21]
Warning: Task "webpack:prod" failed. Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" "--" "--env=prod" "--plugins=hashsum_download"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! girder@2.0.0 build: `grunt init && grunt "--env=prod" "--plugins=hashsum_download"`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the girder@2.0.0 build script 'grunt init && grunt "--env=prod" "--plugins=hashsum_download"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the girder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt init && grunt "--env=prod" "--plugins=hashsum_download"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs girder
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls girder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/girder_env/lib/python2.7/site-packages/girder/npm-debug.log
Traceback (most recent call last):
  File "/root/girder_env/bin/girder-install", line 11, in <module>
    load_entry_point('girder', 'console_scripts', 'girder-install')()
  File "/root/girder_env/local/lib/python2.7/site-packages/girder/utility/install.py", line 294, in main
    parsed.func(parsed)
  File "/root/girder_env/local/lib/python2.7/site-packages/girder/utility/install.py", line 166, in install_web
    plugins=opts.plugins)
  File "/root/girder_env/local/lib/python2.7/site-packages/girder/utility/install.py", line 153, in runWebBuild
    (' '.join(cmd), proc.returncode))
Exception: Web client install failed: `npm run build -- --env=prod --plugins=hashsum_download` returned 1.
```

I can post logs and stuff if you tell me what you'd like to see.

**Comment by zachmullen** [comment] 2016-10-25 12:37
You're the second person to report that error from Uglify. I will try to reproduce it again today.

In the mean time, you can do:

```
cd /root/girder
npm run build -- --plugins=hashsum_download
```

That will build in dev mode rather than production, which skips the uglify step, but produces functionally equivalent output.

**Comment by zachmullen** [comment] 2016-10-25 13:00
What is the output for you of the following command: `npm show uglify version`?

**Comment by nholthaus** [comment] 2016-10-25 13:01
`0.1.5`

**Comment by zachmullen** [comment] 2016-10-25 13:02
And what about `npm show uglify-js version`?

**Comment by nholthaus** [comment] 2016-10-25 13:05
`2.7.4`

**Comment by nholthaus** [comment] 2016-10-25 13:09
`npm run build -- --plugins=hashsum_download` didn't seem to work because of missing dependencies, but just ignoring the uglify error (and using the command line instead of web interface) seemed to be enough to get the plugin enabled for now.

**Comment by zachmullen** [comment] 2016-10-25 13:10
Could you paste the errors you saw from running that command?

**Comment by nholthaus** [comment] 2016-10-25 13:11
```
npm run build -- --plugins=hashsum_download

> girder@2.0.0 build /root/girder
> grunt init && grunt "--plugins=hashsum_download"

Loading "build.js" tasks...ERROR
>> Error: Cannot find module 'underscore'
Loading "plugin.js" tasks...ERROR
>> Error: Cannot find module 'underscore'
Loading "webpack.config.js" tasks...ERROR
>> Error: Cannot find module 'webpack'
Loading "webpack.dev.js" tasks...ERROR
>> Error: Cannot find module 'webpack'
Loading "webpack.prod.js" tasks...ERROR
>> Error: Cannot find module 'webpack'
>> Local Npm module "grunt-shell" not found. Is it installed?
>> Local Npm module "grunt-contrib-watch" not found. Is it installed?
>> Local Npm module "grunt-contrib-stylus" not found. Is it installed?
>> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
>> Local Npm module "grunt-contrib-copy" not found. Is it installed?
>> Local Npm module "grunt-contrib-symlink" not found. Is it installed?
>> Local Npm module "grunt-gitinfo" not found. Is it installed?
>> Local Npm module "grunt-curl" not found. Is it installed?
>> Local Npm module "grunt-zip" not found. Is it installed?
>> Local Npm module "grunt-file-creator" not found. Is it installed?
>> Local Npm module "grunt-npm-install" not found. Is it installed?
>> Local Npm module "grunt-webpack" not found. Is it installed?
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'toposort'
Warning: Task "init" not found. Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" "--" "--plugins=hashsum_download"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE                                                                                                                                                           
npm ERR! girder@2.0.0 build: `grunt init && grunt "--plugins=hashsum_download"`                                                                                                    
npm ERR! Exit status 3                                                                                                                                                             
npm ERR!                                                                                                                                                                           
npm ERR! Failed at the girder@2.0.0 build script 'grunt init && grunt "--plugins=hashsum_download"'.                                                                               
npm ERR! Make sure you have the latest version of node.js and npm installed.                                                                                                       
npm ERR! If you do, this is most likely a problem with the girder package,                                                                                                         
npm ERR! not with npm itself.                                                                                                                                                      
npm ERR! Tell the author that this fails on your system:                                                                                                                           
npm ERR!     grunt init && grunt "--plugins=hashsum_download"                                                                                                                      
npm ERR! You can get information on how to open an issue for this project with:                                                                                                    
npm ERR!     npm bugs girder                                                                                                                                                       
npm ERR! Or if that isn't available, you can get their info via:                                                                                                                   
npm ERR!     npm owner ls girder                                                                                                                                                   
npm ERR! There is likely additional logging output above.                                                                                                                          
                                                                                                                                                                                   
npm ERR! Please include the following file with any support request:                                                                                                               
npm ERR!     /root/girder/npm-debug.log       
```

**Comment by zachmullen** [comment] 2016-10-25 13:13
That's strange, it's looking for modules from 1.x that we depended on like grunt-contrib-stylus. It might be a good idea to `rm -rf node_modules/` and do a fresh `npm install`.

**Comment by nholthaus** [comment] 2016-10-25 13:15
I'll give it a try. For the record, I stood the whole VM/girder instance up yesterday, so I think I should only be using the latest girder.

**Comment by zachmullen** [comment] 2016-10-25 13:16
Ah, that's helpful, how did you spin up the VM? I can try to reproduce the same way.

**Comment by nholthaus** [comment] 2016-10-25 13:19
I used an image of `kubuntu-desktop 14.04`. The only thing we really modify is our proxy environment. I also typically had to edit any `curl` commands to add a `-k` since our proxies self-signed certs seem to interfere with SSL.

we're mostly a `c++` shop so we don't use `npm` for anything except setting up a web server when required, so we shouldn't be getting any weird dependency conflicts.

**Comment by nholthaus** [comment] 2016-10-25 13:21
the fresh `npm install` gave trouble with `phantom-js`, which I think I also saw during the initial install but sucessfully(?) ignored.

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN grunt-webpack@1.0.18 requires a peer of webpack@1.x but none was installed.
npm WARN grunt-webpack@1.0.18 requires a peer of webpack-dev-server@1.x but none was installed.
npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.13 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.13 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/girder/npm-debug.log
```

**Comment by zachmullen** [comment] 2016-10-25 13:29
I haven't seen that error before, and there isn't much of use in that snippet. Maybe the contents of npm-debug.log would be more informative.

For now you can skip the dev dependencies and just do `npm install --unsafe-perms --production`.

You only need the `--unsafe-perms` flag if you are running this as root.

**Comment by mgrauer** [comment] 2016-10-25 13:30
`--unsafe-perm` that is

**Comment by zachmullen** [comment] 2016-10-25 13:31
Yes, sorry.

**Comment by nholthaus** [comment] 2016-10-25 13:36
OK, that helped, got it to build without errors! I've been doing everything as root.

**Comment by nholthaus** [comment] 2016-10-25 19:49
@zachmullen I tested out the merge you guys made, still getting Uglify errors:

```
ERROR in girder.app.min.js from UglifyJs
Unexpected character '`' [girder.app.min.js:5900,317]

ERROR in plugins/item_previews/plugin.min.js from UglifyJs
Unexpected character '`' [plugins/item_previews/plugin.min.js:142,72]

ERROR in plugins/thumbnails/plugin.min.js from UglifyJs
Unexpected character '`' [plugins/thumbnails/plugin.min.js:2349,110]

ERROR in plugins/jobs/plugin.min.js from UglifyJs
Unexpected character '`' [plugins/jobs/plugin.min.js:244,224]

ERROR in plugins/homepage/plugin.min.js from UglifyJs
Unexpected character '`' [plugins/homepage/plugin.min.js:2188,317]
Warning: Task "webpack:prod" failed. Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" "--" "--env=prod" "--plugins=jobs,item_previews,hashsum_download,gravatar,autojoin,metadata_extractor,homepage,thumbnails"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! girder@2.0.0 build: `grunt init && grunt "--env=prod" "--plugins=jobs,item_previews,hashsum_download,gravatar,autojoin,metadata_extractor,homepage,thumbnails"`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the girder@2.0.0 build script 'grunt init && grunt "--env=prod" "--plugins=jobs,item_previews,hashsum_download,gravatar,autojoin,metadata_extractor,homepage,thumbnails"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the girder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt init && grunt "--env=prod" "--plugins=jobs,item_previews,hashsum_download,gravatar,autojoin,metadata_extractor,homepage,thumbnails"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs girder
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls girder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/girder_env/lib/python2.7/site-packages/girder/npm-debug.log
Traceback (most recent call last):
  File "/root/girder_env/bin/girder-install", line 11, in <module>
    load_entry_point('girder', 'console_scripts', 'girder-install')()
  File "/root/girder_env/local/lib/python2.7/site-packages/girder/utility/install.py", line 294, in main
    parsed.func(parsed)
  File "/root/girder_env/local/lib/python2.7/site-packages/girder/utility/install.py", line 166, in install_web
    plugins=opts.plugins)
  File "/root/girder_env/local/lib/python2.7/site-packages/girder/utility/install.py", line 153, in runWebBuild
    (' '.join(cmd), proc.returncode))
Exception: Web client install failed: `npm run build -- --env=prod --plugins=jobs,item_previews,hashsum_download,gravatar,autojoin,metadata_extractor,homepage,thumbnails` returned 1.
```

**Comment by zachmullen** [comment] 2016-10-25 20:09
You were on the latest master when you saw this?

**Comment by nholthaus** [comment] 2016-10-25 20:11
yeah, cb510ae7e44cb92616ef19f7134bcc1eafa11bc6

**Comment by zachmullen** [comment] 2016-10-25 20:22
In my girder.app.min.js inside our docker container that I just spun up, there are no such backticks. Could you show some of the context around those lines in question from your girder.app.min.js file? That might elucidate where they are coming from.

**Comment by nholthaus** [comment] 2016-10-25 20:56
# girder.app.min.js

```
function template(locals) {
  var pug_html = "",
      pug_mixins = {},
      pug_interp;;var locals_for_with = locals || {};(function (enableUploads, placeholder, prefix, text) {
    pug_html = pug_html + "\u003Cdiv class=\"g-markdown-widget\"\u003E\u003Cdiv class=\"g-tabs-container\"\u003E\u003Cdiv class=\"g-markdown-tabs-top\"\u003E\u003Cul class=\"nav $
    if (enableUploads) {
      pug_html = pug_html + "\u003Cdiv class=\"g-upload-overlay hide\"\u003E\u003Cdiv class=\"g-upload-progress-container\"\u003E\u003Cdiv class=\"g-markdown-upload-progress prog$
    }
    pug_html = pug_html + "\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003Cdiv" + (" class=\"tab-pane\"" + " role=\"tabpanel\"" + pug.attr("id", `${ prefix }-preview`, true, true$
  }).call(this, "enableUploads" in locals_for_with ? locals_for_with.enableUploads : typeof enableUploads !== "undefined" ? enableUploads : undefined, "placeholder" in locals_for$
};
module.exports = template;
```

# plugins/item_previews/plugin.min.js

```
function template(locals) {
  var pug_html = "",
      pug_mixins = {},
      pug_interp;;var locals_for_with = locals || {};(function (accessTypes, entry, type) {
    pug_html = pug_html + "\u003Cdiv" + (pug.attr("class", pug.classes([`g-${ type }-access-entry`], [true]), false, true) + pug.attr("resourceid", entry.id, true, true)) + "\u00$
    var icon = type === 'group' ? 'users' : 'user';
    pug_html = pug_html + "\u003Cdiv class=\"g-access-icon\"\u003E\u003Ci" + pug.attr("class", pug.classes([`icon-${ icon }`], [true]), false, true) + "\u003E\u003C\u002Fi\u003E\$
    var sel = null;if (entry.level === accessTypes.READ) sel = 'selected';
    pug_html = pug_html + "\u003Coption" + (pug.attr("value", accessTypes.READ, true, true) + pug.attr("selected", sel, true, true)) + "\u003ECan view\u003C\u002Foption\u003E";
    var sel = null;if (entry.level === accessTypes.WRITE) sel = 'selected';
    pug_html = pug_html + "\u003Coption" + (pug.attr("value", accessTypes.WRITE, true, true) + pug.attr("selected", sel, true, true)) + "\u003ECan edit\u003C\u002Foption\u003E";
    var sel = null;if (entry.level === accessTypes.ADMIN) sel = 'selected';
    pug_html = pug_html + "\u003Coption" + (pug.attr("value", accessTypes.ADMIN, true, true) + pug.attr("selected", sel, true, true)) + "\u003EIs owner\u003C\u002Foption\u003E\u0$
  }).call(this, "accessTypes" in locals_for_with ? locals_for_with.accessTypes : typeof accessTypes !== "undefined" ? accessTypes : undefined, "entry" in locals_for_with ? locals$
};
module.exports = template;
```

# plugins/thumbnails/plugin.min.js:2349,110

```
function template(locals) {
  var pug_html = "",
      pug_mixins = {},
      pug_interp;;var locals_for_with = locals || {};(function (icon, text) {
    pug_html = pug_html + "\u003Cdiv class=\"g-target-result\"\u003E\u003Ci" + pug.attr("class", pug.classes([`icon-${ icon }`], [true]), false, true) + "\u003E\u003C\u002Fi\u003$
  }).call(this, "icon" in locals_for_with ? locals_for_with.icon : typeof icon !== "undefined" ? icon : undefined, "text" in locals_for_with ? locals_for_with.text : typeof text $
};
module.exports = template;
```

# plugins/jobs/plugin.min.js

```
function template(locals) {
  var pug_html = "",
      pug_mixins = {},
      pug_interp;;var locals_for_with = locals || {};(function (endLabel, points, segments, startLabel) {
    pug_html = pug_html + "\u003Cdiv class=\"g-timeline-widget-wrapper\"\u003E\u003Cdiv class=\"g-timeline-container\"\u003E";
    // iterate segments
    ;(function () {
      var $$obj = segments;
      if ('number' == typeof $$obj.length) {
        for (var pug_index0 = 0, $$l = $$obj.length; pug_index0 < $$l; pug_index0++) {
          var segment = $$obj[pug_index0];
          pug_html = pug_html + "\u003Cdiv" + (pug.attr("class", pug.classes(["g-timeline-segment", segment.class], [false, true]), false, true) + pug.attr("title", segment.toolt$
        }
      } else {
        var $$l = 0;
        for (var pug_index0 in $$obj) {
          $$l++;
          var segment = $$obj[pug_index0];
          pug_html = pug_html + "\u003Cdiv" + (pug.attr("class", pug.classes(["g-timeline-segment", segment.class], [false, true]), false, true) + pug.attr("title", segment.toolt$
        }
      }
    }).call(this);
```

# plugins/jobs/plugin.min.js
```
function template(locals) {
  var pug_html = "",
      pug_mixins = {},
      pug_interp;;var locals_for_with = locals || {};(function (enableUploads, placeholder, prefix, text) {
$ntent\"\u003E\u003Cdiv" + (" class=\"tab-pane active\"" + " role=\"tabpanel\"" + pug.attr("id", `${ prefix }-write`, true, true)) + "\u003E\u003Cdiv class=\"g-markdown-drop-zone$
    if (enableUploads) {
      pug_html = pug_html + "\u003Cdiv class=\"g-upload-overlay hide\"\u003E\u003Cdiv class=\"g-upload-progress-container\"\u003E\u003Cdiv class=\"g-markdown-upload-progress prog$
    }
    pug_html = pug_html + "\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003Cdiv" + (" class=\"tab-pane\"" + " role=\"tabpanel\"" + pug.attr("id", `${ prefix }-preview`, true, true$
  }).call(this, "enableUploads" in locals_for_with ? locals_for_with.enableUploads : typeof enableUploads !== "undefined" ? enableUploads : undefined, "placeholder" in locals_for$
};
module.exports = template;
```

**Comment by zachmullen** [comment] 2017-01-28 15:00
Closing this issue since the original question was addressed. If you still have problems with the docker image, please reopen as a separate issue.

**Closed by zachmullen** 2017-01-28 15:00 UTC
