### ISSUE TITLE
Access to QIDW Data Warehouse

### ISSUE THREAD

**Issue by avivekan** [girder/girder#1763] opened 2017-01-26 22:54 UTC
Hello,

I'm trying to access QIDW data inventory to compare my segmentations with QIBA standards. However, after creating an account (avivekan, ajeet@healthmyne.com) I get an Access Denied error, saying to check the console for details. Can you please let me know what I need to do to retrieve the RIDER dataset from QIDW?

**Comment by mgrauer** [comment] 2017-01-27 03:00
Hi @avivekan ,

That instance of Girder is run by the RSNA.  I've forwarded your contact info along to them, so they can give you some guidance about whether you can and how to access that dataset.

I'm going to close this issue, as it is not a bug with Girder itself.  If you are getting an Access Denied error, that is due to how their particular instance permissions are configured, and the software itself is operating correctly.

**Closed by mgrauer** 2017-01-27 03:00 UTC
